language: java
jdk:
    - oraclejdk8
deploy:
    provider: heroku
    api-key:
        secure: $HEROKU_API_KEY
    app: sysc4806-ama
env:
  - NODE_VERSION="6"

before_install:
  - nvm install $NODE_VERSION

install: 
    - npm install karma
